require('dotenv').config();
module.exports = {
  SESSION: process.env.SESSION || '',
  OWNER_NUMBER: (process.env.OWNER_NUMBER || '').replace(/\D/g, ''),
  DEVELOPERS: (process.env.DEVELOPERS || '').split(',').map(n => n.replace(/\D/g, '')).filter(Boolean),
  BOT_NAME: process.env.BOT_NAME || 'Deadpool V7',
  OWNER_NAME: process.env.OWNER_NAME || 'Confronter',
  PREFIX: process.env.PREFIX || '!',
  MODE: (process.env.MODE || 'public').toLowerCase(),
  WELCOME: (process.env.WELCOME || 'false').toLowerCase() === 'true',
  GOODBYE: (process.env.GOODBYE || 'false').toLowerCase() === 'true',
  WELCOME_MSG: process.env.WELCOME_MSG || '⚔️ *Entry granted*\n*{name}* ({phone}) stepped into *{group}*.\n\n📜 Rules are not suggestions — obey them or leave with dignity.',
  GOODBYE_MSG: process.env.GOODBYE_MSG || '🚪 *Departure logged*\n*{name}* ({phone}) left *{group}*.',
  AUTO_VIEW_STATUS: (process.env.AUTO_VIEW_STATUS || 'true').toLowerCase() === 'true',
  AUTO_LIKE_STATUS: (process.env.AUTO_LIKE_STATUS || 'false').toLowerCase() === 'true',
  STATUS_LIKES: (process.env.STATUS_LIKES || '❤️,🔥,💯').split(',').map(s => s.trim()).filter(Boolean),
  AUTO_READ: (process.env.AUTO_READ || 'false').toLowerCase() === 'true',
  ANTI_DELETE: (process.env.ANTI_DELETE || 'pm').toLowerCase(),
  ANTI_CALL: (process.env.ANTI_CALL || 'true').toLowerCase() === 'true',
  ANTI_CALL_MSG: process.env.ANTI_CALL_MSG || 'Calls are closed. Use text.',
  ANTILINK: (process.env.ANTILINK || 'false').toLowerCase() === 'true',
  PRESENCE: (process.env.PRESENCE || 'available').toLowerCase(),
  POWERED_BY: process.env.POWERED_BY || 'Powered by Confronter',
  AUTO_JOIN_GROUPS: (process.env.AUTO_JOIN_GROUPS || '').split(',').map(s => s.trim()).filter(Boolean),
  AUTO_JOIN_CHANNEL: process.env.AUTO_JOIN_CHANNEL || '',
  BOT_EXPIRY_DAYS: parseInt(process.env.BOT_EXPIRY_DAYS || '0', 10) || 0,
  BOT_EXPIRY_DATE: process.env.BOT_EXPIRY_DATE || '',
  BOT_ACTIVATED_AT: process.env.BOT_ACTIVATED_AT || '',
  EXPIRY_MSG: process.env.EXPIRY_MSG || '⛔ Bot duration expired. Contact owner.'
};
